/**
 * GENERATED by scripts/fetch-anime-characters.js — do not hand-edit.
 * Vendored original-series anime character art for "Aventures" mode. See
 * public/anime/CHARACTERS.LICENSE.txt for source/licensing.
 */
const BASE = import.meta.env.BASE_URL

export const CHARACTERS = [
  { id: 'ash', label: "Ash Ketchum" },
  { id: 'misty', label: "Misty" },
  { id: 'brock', label: "Brock" },
  { id: 'oak', label: "Professor Oak" },
  { id: 'team-rocket', label: "Team Rocket (Jessie, James, Meowth)" },
]

/** A vendored anime character portrait by id (see CHARACTERS above), or null for an unknown id. */
export function characterUrl(id) {
  return CHARACTERS.some(c => c.id === id) ? `${BASE}anime/${id}.webp` : null
}
