#!/usr/bin/env node
/**
 * Vendor the three project typefaces into public/fonts/ and generate src/fonts.css.
 *
 * The play app is an offline PWA and "narration legible for an adult at arm's length" is a
 * P0 criterion — a CDN font that silently fails to arrive would degrade to a system fallback
 * with different metrics. Self-hosting also removes the last third-party request.
 *
 * Only the `latin` and `latin-ext` subsets are pulled; Catalan's ·, ç and accented vowels
 * all live there.
 *
 * Usage: node scripts/fetch-fonts.js
 */

import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const FONT_DIR = path.join(ROOT, 'public', 'fonts')
const CSS_OUT = path.join(ROOT, 'src', 'fonts.css')

// A modern UA is what makes Google Fonts serve woff2 instead of ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'

const FAMILIES = [
  { css: 'Barlow+Condensed:wght@700;800;900', slug: 'barlow-condensed' },
  { css: 'Lora:ital,wght@0,400;0,600;1,400',  slug: 'lora' },
  { css: 'Space+Mono:wght@400;700',           slug: 'space-mono' },
]

const WANTED_SUBSETS = new Set(['latin', 'latin-ext'])

/** Split the Google CSS into `/* subset *\/ @font-face { ... }` records. */
function parseFaces(css) {
  const faces = []
  const re = /\/\*\s*([\w[\]-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g
  let m
  while ((m = re.exec(css))) {
    const [, subset, body] = m
    const field = name => body.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim()
    const url = body.match(/url\((https:[^)]+)\)/)?.[1]
    faces.push({
      subset,
      url,
      family: field('font-family')?.replace(/^['"]|['"]$/g, ''),
      style: field('font-style') ?? 'normal',
      weight: field('font-weight') ?? '400',
      unicodeRange: field('unicode-range'),
    })
  }
  return faces
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true })

  const blocks = []

  for (const { css, slug } of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${css}&display=swap`
    const res = await fetch(url, { headers: { 'User-Agent': UA } })
    if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`)
    const faces = parseFaces(await res.text()).filter(f => WANTED_SUBSETS.has(f.subset))
    if (!faces.length) throw new Error(`no latin faces parsed for ${css}`)

    for (const face of faces) {
      const italic = face.style === 'italic' ? 'italic' : 'normal'
      const file = `${slug}-${face.weight}-${italic}-${face.subset}.woff2`
      const bin = await fetch(face.url, { headers: { 'User-Agent': UA } })
      if (!bin.ok) throw new Error(`${face.url} → HTTP ${bin.status}`)
      await writeFile(path.join(FONT_DIR, file), Buffer.from(await bin.arrayBuffer()))

      blocks.push(
        [
          '@font-face {',
          `  font-family: '${face.family}';`,
          `  font-style: ${face.style};`,
          `  font-weight: ${face.weight};`,
          '  font-display: swap;',
          `  src: url('/fonts/${file}') format('woff2');`,
          face.unicodeRange ? `  unicode-range: ${face.unicodeRange};` : null,
          '}',
        ]
          .filter(Boolean)
          .join('\n'),
      )
      console.log(`  ${file}`)
    }
  }

  const header = [
    '/* Generated by scripts/fetch-fonts.js — do not edit by hand.',
    '   Self-hosted so the app renders correctly offline and makes no third-party requests. */',
    '',
  ].join('\n')

  await writeFile(CSS_OUT, `${header}${blocks.join('\n\n')}\n`)
  console.log(`\n${blocks.length} faces → src/fonts.css`)
}

main()
